name: FCIChat
version: 1.3
author: Filip Zocktan
main: me.filipzocktan.fcicrafting.FCICrafting
commands:
  fcicr:
    description: Zeigt Plugininfo an.
  fcicrafting:
    description: Zeigt Plugininfo an.
  fortresscombat1crafting:
    description: Zeigt Plugininfo an.