name: FCICrafting
version: 1.1 pre 3
author: Filip Zocktan
main: me.filipzocktan.fcicrafting.FCICrafting
commands:
  fcicr:
    description: Zeigt Plugininfo an.
  fcicrdev:
    description: Zeigt Plugininfo an.
  fcicrafting:
    description: Zeigt Plugininfo an.
  fortresscombat1crafting:
    description: Zeigt Plugininfo an.
  gefs:
    description: Erhalte ein EffectSword
  geteffectsword:
    description: Erhalte ein EffectSword